require("joesuzuki.plugins-setup")
require("joesuzuki.core.options")
require("joesuzuki.core.keymaps")
require("joesuzuki.core.colorscheme")
require("joesuzuki.plugins.comment")
require("joesuzuki.plugins.nvim-tree")
require("joesuzuki.plugins.lualine")
require("joesuzuki.plugins.telescope")
require("joesuzuki.plugins.nvim-cmp")
require("joesuzuki.plugins.lsp.mason")
require("joesuzuki.plugins.lsp.lspsaga")
require("joesuzuki.plugins.lsp.lspconfig")
require("joesuzuki.plugins.lsp.null-ls")
require("joesuzuki.plugins.autopairs")
require("joesuzuki.plugins.treesitter")
require("joesuzuki.plugins.gitsigns")
-- require("joesuzuki.plugins.lang.haskell")
